runtime: nodejs18
availableSecrets:
  secretManager:
  - versionName: projects/playpal-63bee/secrets/GRID_KEY/versions/latest
    env: 'GRID_KEY'
  - versionName: projects/playpal-63bee/secrets/PALM_KEY/versions/latest
    env: 'PALM_KEY'
  - versionName: projects/playpal-63bee/secrets/STEAM_KEY/versions/latest
    env: 'STEAM_KEY'
  - versionName: projects/playpal-63bee/secrets/RAWG_KEY/versions/latest
    env: 'RAWG_KEY'