steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
  secretEnv: ['GRID_KEY', 'PALM_KEY', 'STEAM_KEY', 'RAWG_KEY']
timeout: '1600s'
availableSecrets:
  secretManager:
  - versionName: projects/741034783195/secrets/GRID_KEY
    env: 'GRID_KEY'
  - versionName: projects/741034783195/secrets/PALM_KEY
    env: 'PALM_KEY'
  - versionName: projects/741034783195/secrets/STEAM_KEY
    env: 'STEAM_KEY'
  - versionName: projects/741034783195/secrets/RAWG_KEY
    env: 'RAWG_KEY'
